# Generated by Django 4.2.5 on 2023-09-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('preview_img', models.ImageField(upload_to='blog/images/', verbose_name='Превью')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Признак публикации')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
            ],
        ),
    ]
