# Generated by Django 4.2.5 on 2023-10-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Превью'),
        ),
    ]
