# Generated by Django 4.2.5 on 2023-10-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_clientservice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
