# Generated by Django 4.2.5 on 2023-10-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mailinglog_attempt_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='mailing',
        ),
    ]
